version: "2"
apiVersion: v1
kind: PersistentVolume
metadata:
  name: statefulset-pgdata
  labels:
    name: statefulset-pgdata
spec:
  capacity:
    storage: "400M"
  accessModes:
  - "ReadWriteMany"
  hostPath:
    path: "/nfsfileshare"
  persistentVolumeReclaimPolicy: Retain
