version: "2"
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: statefulset
spec:
  serviceName: statefulset
  replicas: 2
  template:
    metadata:
      labels:
        app: statefulset
    spec:
      serviceAccount: statefulset-sa
      securityContext:
        supplementalGroups:
        - 65534
      containers:
      - name: statefulset
        image: "crunchydata/crunchy-postgres:centos7-10.3-1.8.2"
        ports:
        - containerPort: 5432
          name: postgres
        env:
        - name: PG_PRIMARY_USER
          value: primaryuser
        - name: PG_MASTER_USER
          value: primaryuser
        - name: PGHOST
          value: "/tmp"
        - name: PG_MODE
          value: set
        - name: PG_PRIMARY_HOST
          value: statefulset-primary
        - name: PG_REPLICA_HOST
          value: statefulset-replica
        - name: PG_PRIMARY_PORT
          value: '5432'
        - name: PG_PRIMARY_PASSWORD
          value: password
        - name: PG_USER
          value: testuser
        - name: PG_PASSWORD
          value: password
        - name: PG_DATABASE
          value: userdb
        - name: PG_ROOT_PASSWORD
          value: password
        volumeMounts:
        - name: pgdata
          mountPath: "/pgdata"
          readOnly: false
      volumes:
      - name: pgdata
        persistentVolumeClaim:
          claimName: statefulset-pgdata
