version: "2"
catalog:
  version: 0
  minimum_rancher_version: 1.6.0
  questions:
    - variable: BUILD
      label: Build Number
      description: The build number of the Cadas to deploy
      required: true
      default: latest
      type: string
    - variable: APP_PORT
      label: APP Port
      required: true
      default: 7009
      type: string
    - variable: DB_PORT
      label: DB Port
      required: true
      default: 7019
      type: string
