name: 123 Software Crunchy PostgreSQL Containers
description: |
  Deploys Crunchy PostgreSQL Containers in Rancher in 123 Software
version: 1
category: Crunchy
maintainer: Ruslan Shevchenko <ruslansh@123software.ru>